# Generated by Django 2.0.5 on 2019-12-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refillr_backend_app', '0004_auto_20191219_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='location_images/'),
        ),
    ]
