# Generated by Django 2.0.5 on 2020-01-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refillr_backend_app', '0006_auto_20200107_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
